name: Android CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  release:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Build release for all modules
        run: |
          ./gradlew :robok-gui:assembleRelease --stacktrace
          ./gradlew :robok-antlr4:assembleRelease --stacktrace
          ./gradlew :app:assembleRelease --stacktrace

      - name: Upload release library-gui
        uses: actions/upload-artifact@v4
        with:
          name: library-gui
          path: robok-gui/build/
          
      - name: Upload release library-antlr4
        uses: actions/upload-artifact@v4
        with:
          name: library-antlr
          path: robok-antlr4/build/
          
      - name: Upload release app
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/

  debug:
    name: Build Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Build debug for all modules
        run: |
          ./gradlew :robok-gui:assembleDebug --stacktrace
          ./gradlew :robok-antlr4:assembleDebug --stacktrace
          ./gradlew :app:assembleDebug --stacktrace

      - name: Upload debug library-gui
        uses: actions/upload-artifact@v4
        with:
          name: library-gui-debug
          path: robok-gui/build/
          
      - name: Upload debug library-antlr4
        uses: actions/upload-artifact@v4
        with:
          name: library-antlr-debug
          path: robok-antlr4/build/
          
      - name: Upload debug app
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/
